name: SAST validation

on:
  pull_request:
    paths:
      - 'src/**'

jobs:
  sast:
    name: Validate code
    uses: michal-worwag/course-actions/.github/workflows/sast-validation-semgrep.yaml@main
    with:
      rules: 'p/typescript'
      upload-artifact: true
      upload-release-assets: false
      upload-results-github-security: false
